// File autogenerated by bdf2js.py

const name = "9x15";
const width = 9;
const height = 15;
const depth = 1;
const colours = [ "#000000ff", "#ffffffff" ];
const pages = new Set([ 0, 1, 2, 3, 4, 5, 6, 14, 16, 18, 19, 22, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 46, 48, 224, 231, 251, 254, 255 ]);
const properties = [ 'name', 'width', 'height', 'depth', 'colours', 'pages' ];

export { name, width, height, depth, colours, pages, properties };

